import Head from 'next/head';
import React from 'react';
import Hero7 from '../components/Hero/Hero7';
import Layout from '../components/Layout';

export default function CaseStudyShowcase() {
  const heroSocialLinks = [
    {
      name: 'Behance',
      links: '/',
    },
    {
      name: 'Twitter',
      links: '/',
    },
  ];

  const showcaseData = [
    {
      title: 'Uber food app <br />case study',
      imgUrl: '/images/slider_5.jpeg',
      href: '/case-study-details',
    },
    {
      title: 'Uber food app <br />case study',
      imgUrl: '/images/slider_6.jpeg',
      href: '/case-study-details',
    },
    {
      title: 'Uber food app <br />case study',
      imgUrl: '/images/slider_7.jpeg',
      href: '/case-study-details',
    },
    {
      title: 'Uber food app <br />case study',
      imgUrl: '/images/slider_8.jpeg',
      href: '/case-study-details',
    },
    {
      title: 'Uber food app <br />case study',
      imgUrl: '/images/slider_9.jpeg',
      href: '/case-study-details',
    },
  ];
  return (
    <>
      <Head>
        <title>Home - Case Study Showcase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero7
          heroSocialLinks={heroSocialLinks}
          socialLinksHeading="Follow Us"
          showcaseData={showcaseData}
        />
      </Layout>
    </>
  );
}
