import Head from 'next/head';
import Card from '../components/Card';
import Cta from '../components/Cta';
import Div from '../components/Div';
import FunFact from '../components/FunFact';
import Hero from '../components/Hero';
import Layout from '../components/Layout';
import LogoList from '../components/LogoList';
import MovingText from '../components/MovingText';
import SectionHeading from '../components/SectionHeading';
import PortfolioSlider from '../components/Slider/PortfolioSlider';
import PostSlider from '../components/Slider/PostSlider';
import TeamSlider from '../components/Slider/TeamSlider';
import TestimonialSlider from '../components/Slider/TestimonialSlider';
import TimelineSlider from '../components/Slider/TimelineSlider';
import Spacing from '../components/Spacing';
import VideoModal from '../components/VideoModal';

export default function Home() {
  // Hero Social Links
  const heroSocialLinks = [
    {
      name: 'Instagram',
      links: '/',
    },
    {
      name: 'Twitter',
      links: '/',
    },
    {
      name: 'Linkedin',
      links: '/'
    },
  ];

  // FunFact Data
  const funfaceData = [

    {
      title: 'Events Covered',
      factNumber: '300+',
    },
    {
      title: 'Team Members',
      factNumber: '109',
    },
    {
      title: 'Paintings And Decorations',
      factNumber: '50+',
    },
    {
      title: 'Creatives Designed',
      factNumber: '1500+'
    }
  ];

  return (
    <>
      <Head>
        <title>Kreative Eye</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Start Hero Section */}
        <Hero
          title="Kreative Eye"
          subtitle="Welcome to"
          scrollDownId="#service"
          socialLinksHeading="Follow Us"
          heroSocialLinks={heroSocialLinks}
          bgImageUrl="/images/hero_bg.jpeg"
        />

        {/* End Hero Section */}

        {/* Start FunFact Section */}
        <div className="container">
          <FunFact
            variant="cs-type1"
            title="Our fun fact"
            subtitle="Sed ut perspiciatis unde omnis iste natus error voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis."
            data={funfaceData}
          />
        </div>
        {/* End FunFact Section */}

        {/* Start Portfolio Section */}
        <Spacing lg="150" md="50" />
        <Div>
          <Div className="container">
            <SectionHeading
              title="Portfolio to explore"
              subtitle="Latest Projects"
              variant="cs-style1 text-center"
            />
            <Spacing lg="90" md="45" />
          </Div>
          <PortfolioSlider />
        </Div>
        {/* End Portfolio Section */}

        {/* Start Awards Section */}
        <Spacing lg="150" md="80" />
        <Div className="cs-shape_wrap_2">
          <Div className="cs-shape_2">
            <Div />
          </Div>
          <Div className="container">
            <Div className="row">
              <Div className="col-xl-4">
                <SectionHeading
                  title="We get multiple awards"
                  subtitle="Our Awards"
                  variant="cs-style1"
                />
                <Spacing lg="90" md="45" />
              </Div>
              <Div className="col-xl-7 offset-xl-1">
                <TimelineSlider />
              </Div>
            </Div>
          </Div>
        </Div>
        {/* End Awards Section */}

        {/* Start Video Block Section */}
        <Spacing lg="130" md="70" />
        <Div className="container">
          <h2 className="cs-font_50 cs-m0 text-center cs-line_height_4">
            "Through the lens of creativity and the magic of teamwork,
            KIIT <span className="text-weight-bold text"> Kreative Eye</span> illuminates our college's stories. Together, we capture memories and paint them with the vibrant colors of passion."
          </h2>
          <Spacing lg="70" md="70" />
          <VideoModal/>
        </Div>
        {/* End Video Block Section */}

        {/* Start Team Section */}
        <Spacing lg="145" md="80" />
        <Div className="container text-center">
        <SectionHeading
            title="Our Team"
            subtitle=""
            variant="cs-style1"
        />
        </Div>
        <Spacing lg="80" md="30" />
        <Div className="container">
          <SectionHeading
              title="Leads"
              subtitle="Meet The"
              variant="cs-style1"
          />
          <Spacing lg="85" md="45" />
          <TeamSlider />
          <Spacing lg="85" md="45" />

        </Div>
        <Div className="container">
          <SectionHeading
              title="Ex-Leads"
              subtitle="Meet The"
              variant="cs-style1"
          />
          <Spacing lg="85" md="45" />
          <TeamSlider />
          <Spacing lg="85" md="45" />

        </Div>
        <Spacing lg="150" md="80" />
        {/* End Team Section */}

        {/* Start Testimonial Section */}
        <Div className="container text-center">
          <SectionHeading
              title="Testimonials"
              subtitle=""
              variant="cs-style1"
          />
        </Div>
        <Spacing lg="50" md="10" />
        <TestimonialSlider />
        {/* End Testimonial Section */}



        {/* Start MovingText Section */}
        <Spacing lg="125" md="70" />
        <MovingText text="Our reputed world wide partners" />
        <Spacing lg="105" md="70" />
        {/* End MovingText Section */}

        {/* Start LogoList Section */}
        <Div className="container">
          <LogoList />
        </Div>
        <Spacing lg="150" md="80" />
        {/* End LogoList Section */}

        {/* Start CTA Section */}
        <Div className="container">
          <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          />
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
