import Head from 'next/head';
import React from 'react';
import Hero6 from '../components/Hero/Hero6';
import Layout from '../components/Layout';

export default function ShowcasePortfolio() {
  const heroSocialLinks = [
    {
      name: 'Behance',
      links: '/',
    },
    {
      name: 'Twitter',
      links: '/',
    },
  ];

  const showcaseData = [
    {
      title: 'Think reality <br/>do positive',
      imgUrl: '/images/slider_1.jpeg',
      href: '/case-study-details',
    },
    {
      title: 'Think reality <br/>do positive',
      imgUrl: '/images/slider_2.jpeg',
      href: '/case-study-details',
    },
    {
      title: 'Think reality <br/>do positive',
      imgUrl: '/images/slider_3.jpeg',
      href: '/case-study-details',
    },
    {
      title: 'Think reality <br/>do positive',
      imgUrl: '/images/slider_4.jpeg',
      href: '/case-study-details',
    },
  ];
  return (
    <>
      <Head>
        <title>Home - Showcase Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero6
          heroSocialLinks={heroSocialLinks}
          socialLinksHeading="Follow Us"
          showcaseData={showcaseData}
        />
      </Layout>
    </>
  );
}
